clusterZone: "cluster.local"
master:
  componentName: "jenkins-master"
  image: "jenkins/jenkins"
  tag: "lts"
  imagePullPolicy: "Always"
  numExecutors: 0
  useSecurity: true
  enableXmlConfig: true
  securityRealm: |-
    <securityRealm class="hudson.security.LegacySecurityRealm"/>
  authorizationStrategy: |-
     <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
       <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
     </authorizationStrategy>
  hostNetworking: false
  adminUser: "admin"
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  usePodSecurityContext: true
  servicePort: 8080
  targetPort: 8080
  serviceType: ClusterIP
  healthProbes: true
  healthProbesLivenessTimeout: 5
  healthProbesReadinessTimeout: 5
  healthProbeLivenessPeriodSeconds: 10
  healthProbeReadinessPeriodSeconds: 10
  healthProbeLivenessFailureThreshold: 5
  healthProbeReadinessFailureThreshold: 3
  healthProbeLivenessInitialDelay: 90
  healthProbeReadinessInitialDelay: 60
  slaveListenerPort: 50000
  slaveHostPort:
  disabledAgentProtocols:
    - JNLP-connect
    - JNLP2-connect
  csrf:
    defaultCrumbIssuer:
      enabled: true
      proxyCompatability: true
  cli: false
  slaveListenerServiceType: "ClusterIP"
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
  JCasC:
    enabled: false
    defaultConfig: false
    pluginVersion: "1.32"
    supportPluginVersion: "1.18"
    configScripts: {}
  customInitContainers: []
  ingress:
    enabled: true
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.fjorg10xc3bde0.sbx.thecommons.nike.com
    tls:
  prometheus:
    enabled: false
    serviceMonitorAdditionalLabels: {}
    scrapeInterval: 60s
    scrapeEndpoint: /prometheus
    alertingRulesAdditionalLabels: {}
    alertingrules: []
  testEnabled: true
agent:
  enabled: true
  image: "jenkins/jnlp-slave"
  tag: "3.27-1"
  componentName: "jenkins-slave"
  privileged: false
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  alwaysPullImage: false
  podRetention: "Never"
  sideContainerName: "jnlp"
  TTYEnabled: false
  containerCap: 10
  podName: "slave"
  idleMinutes: 0
  yamlTemplate: ""
  slaveConnectTimeout: 100
persistence:
  enabled: true
  existingClaim: "pv2-pvc1"
  accessMode: "ReadWriteOnce"
  size: "8Gi"
rbac:
  create: true
  readSecrets: false
serviceAccount:
  create: true
  name: jenkins
checkDeprecation: true
